[env:pc]
platform = native
build_flags =
    -DPLATFORM_PC

[env:esp]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L
framework = arduino
monitor_speed = 115200

build_flags =
    -DPLATFORM_ESP
    -Iinclude
    -Icore
    -Iexternal/nlohmann

lib_deps =
    earlephilhower/ESP8266Audio

