[platformio]
default_envs = esp

[env]
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17
    -Iinclude
    -Iexternal

lib_ldf_mode = deep+

lib_deps =
    earlephilhower/ESP8266Audio


# ==========================
# Main ESP build
# ==========================
[env:esp]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L

build_flags =
    ${env.build_flags}
    -DPLATFORM_ESP

; Only build main app (libs are automatic)
build_src_filter =
    +<main.cpp>
    -<tests/>


# ==========================
# Storage test
# ==========================
[env:esp_storage_test]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L

build_flags =
    ${env.build_flags}
    -DPLATFORM_ESP

build_src_filter =
    -<*>
    +<tests/platform/esp8266/StorageTest.cpp>



[env:esp_input_calibration]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L

build_flags =
    ${env.build_flags}
    -DPLATFORM_ESP

build_src_filter =
    -<*>
    +<tests/platform/esp8266/AnalogLadderCalibration.cpp>


# ==========================
# Input test
# ==========================
[env:esp_input_test]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L

build_flags =
    ${env.build_flags}
    -DPLATFORM_ESP

build_src_filter =
    -<*>
    +<tests/platform/esp8266/ESPInputTest.cpp>