//
// Created by user on 4/13/2026.
//

#ifndef BLASTER_FIRMWARE_BASICWEAPONCONTROLLER_H
#define BLASTER_FIRMWARE_BASICWEAPONCONTROLLER_H


class BasicWeaponController {
};


#endif //BLASTER_FIRMWARE_BASICWEAPONCONTROLLER_H